### ISSUE TITLE
MySQL not importing ?

### ISSUE THREAD

**Issue by IlPicasso** [Synapz1/Paintball#42]
I tried compiling the plugin from here , and then I bought and MySQL is not working. This is the error

[12:30:37 WARN]: Exception in thread "Craft Scheduler Thread - 32"
[12:30:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin Paintball v1.0.7 generated an exception while executing task 45
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at me.synapz.paintball.storage.database.ConnectionPool.getConnection(ConnectionPool.java:40)
        at me.synapz.paintball.storage.database.DatabaseManager.getConnection(DatabaseManager.java:27)
        at me.synapz.paintball.storage.database.DatabaseManager.updateTable(DatabaseManager.java:50)
        at me.synapz.paintball.storage.files.UUIDStatsFile.lambda$saveAsynchronously$0(UUIDStatsFile.java:82)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more

**Comment by Synapz1** [comment]
Yep MySQL was disabled. Everything works I just have to figure out how to shade in the database API we use with the plugin

**Comment by IlPicasso** [comment]
any ETA for re enabling this ?

**Comment by Synapz1** [comment]
Not yet. I am trying to figure out how to shade in the jar correctly

**Comment by Synapz1** [comment]
Alright everything now complies without having to import anything. Make sure to compile with maven shade plugin and package with maven shade plugin. MySQL was also re-enabled as everything is now shaded in correctly and working great.
